import type { Metadata } from "next";
import "./globals.scss";
import localFont from "next/font/local";

const geograph = localFont({
  src: [
    {
      path: "./font/test-geograph-vf-roman.woff2",
      style: "normal",
      weight: "100 900",
    },
    {
      path: "./font/test-geograph-vf-italic.woff2",
      style: "italic",
      weight: "100 900",
    },
  ],
  variable: "--font-app",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geograph.variable}`}>{children}</body>
    </html>
  );
}
